apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: currency-converter-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # This specifies the Ingress class
  rules:
  - host: currency.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: currency-converter
            port:
              number: 80

