apiVersion: v1
kind: Service
metadata:
  name: currency-converter
spec:
  type: NodePort
  selector:
    app: currency-converter
  ports:
    - name: http
      port: 80          # This is the port that the service exposes
      targetPort: 8080  # This is the port on the container
      nodePort: 30477   # This is the NodePort

