name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3
      - name: Build
        run: go build -o currency-converter
      - name: Test
        run: go test ./...

  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/currency-converter:${{ github.run_id }}

  update_newtag_in_helm_chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/currency-converter-chart/values.yaml
      - name: Commit and push changes
        run: |
          git config --global user.email "nishitm060@gmail.com"
          git config --global user.name "Pushkar Mondal"
          git add helm/currency-converter-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
